config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home', as: :home
  get 'user/new_html', to: 'user#new_html', as: :new_html
  post 'user/new_html', to: 'user#create_html', as: :create_html
  get 'user/new_form_tag', to: 'user#new_form_tag', as: :new_form_tag
  post 'user/new_form_tag', to: 'user#create_form_tag', as: :create_form_tag
  get 'user/new_form_for', to: 'user#new_form_for', as: :new_form_for
  post 'user/new_form_for', to: 'user#create_form_for', as: :create_form_for
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: {message: "You need to enter a username"}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new_html
    @user = User.new
  end

  def create_html
    user = User.new
    user.username = params[:username]
    user.email = params[:email]
    user.bio = params[:bio]
    user.save
    @user = user
    if @user.valid?
    else
      render 'new_html'
    end
  end

  def new_form_tag
    @user = User.new
  end

  def create_form_tag
    user = User.new
    user.username = params[:username]
    user.email = params[:email]
    user.bio = params[:bio]
    user.save
    @user = user
    if @user.valid?
    else
      render 'new_form_tag'
    end
  end

  def new_form_for
    @user = User.new
  end

  def create_form_for
    @user = User.new
    @user.username = params[:user][:username]
    @user.email = params[:user][:email]
    @user.bio = params[:user][:bio]
    @user.save
    if @user.valid?
    else
      render 'new_form_for'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LovingForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </head>

  <body>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-center">
          <a href="<%= home_path %>" class="navbar-brand d-flex align-items-center">
            <strong>Home</strong>
          </a>
          <a href="<%= new_html_path %>" class="navbar-brand d-flex align-items-center">
            <strong>👻</strong>
          </a>
          <a href="<%= new_form_tag_path %>" class="navbar-brand d-flex align-items-center">
            <strong>👽</strong>
          </a>
          <a href="<%= new_form_for_path %>" class="navbar-brand d-flex align-items-center">
            <strong>💀</strong>
          </a>
        </div>
      </div>

    <div class="container" style="padding-top: 3em; text-align: center">
    <%= yield %>
  </body>
</html>

app/views/user/create_form_for.html.erb
<h1>💀</h1>
<h3>Welcome dear <%= @user.username %> !</h3> <br>
<h5>Congrats ! <br>
You have just stepped in the marvellous world of role play with movie fans !</h5>
<br>
<p>To go back home, please click <a href="<%= home_path %>">here</a></p>

app/views/user/create_form_tag.html.erb
<h1>👽</h1>
<h3>Welcome dear <%= @user.username %> !</h3> <br>
<h5>Congrats ! <br>
You have just stepped in the marvellous world of role play with movie fans !</h5>
<br>
<p>To go back home, please click <a href="<%= home_path %>">here</a></p>

app/views/user/create_html.html.erb
<h1>👻</h1>
<h3>Welcome dear <%= @user.username %> !</h3> <br>
<h5>Congrats ! <br>
You have just stepped in the marvellous world of role play with movie fans !</h5>
<br>
<p>To go back home, please click <a href="<%= home_path %>">here</a></p>

app/views/user/new_form_for.html.erb
<h1>💀</h1>
<h3>🎙 Ready to start ? 📽</h3> <br>
<h5>So fill up the form with the specifications of the character you wanna be !</h5>
<br>

<%= form_for @user, url: {action: "create_form_for"} do |f| %>
  <%= field_set_tag 'Choose your favorite movie character' do %>
    Name of your movie character : <br>
    <%= f.text_field :username, class: "col-4", placeholder: "Your great name" %>
    <p>
    <% if @user.invalid? %>
      <div class="alert-primary">
        <% @user.errors[:username].each do |message| %>
        <%= message %>
        <% end %>
      </div>
    <% end %>
    </p>
    <br>

    Your email address : <br>
    <%= f.email_field(:email, option = {class: "col-5", placeholder: "Your email"})%> <br> <br>
    The biography of your character : <br>
    <%= f.text_area :bio, size: "40x5", placeholder: "Your incredible story.." %> <br> <br>
    <%= f.submit "Let's play !"  %>
  <% end %>
<% end %>

app/views/user/new_form_tag.html.erb
<h1>👽</h1>
<h3>🎙 Ready to start ? 📽</h3> <br>
<h5>So fill up the form with the specifications of the character you wanna be !</h5>
<br>

<%= form_tag url_for(action: 'create_form_tag'), method: "post" do  %>
  <%= field_set_tag 'Choose your favorite movie character' do %>
    <p>Name of your movie character : <br>
    <%= text_field_tag 'username'  %></p>
    <p>
    <% if @user.invalid? %>
      <div class="alert-primary">
        <% @user.errors[:username].each do |message| %>
        <%= message %>
        <% end %>
      </div>
    <% end %>
    </p>
    <br>
    <p>Your email address : <br>
    <%= email_field_tag 'email' %></p>
    <p>The biography of your character : <br>
    <%= text_area_tag 'bio', nil, rows: 10, cols: 30 %></p>
    <%= submit_tag "Let's play!" %>
  <% end %>
<% end %>

app/views/user/new_html.html.erb
<h1>👻 </h1>
<h3>🎙 Ready to start ? 📽</h3> <br>
<h5>So fill up the form with the specifications of the character you wanna be !</h5>
<br>

<form action="<%= new_html_path %>" method="post" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <fieldset>
    <legend> Choose your favorite movie character </legend><br>
    Name of your movie character : <br>
    <input type="text" name="username"><br>
    <p>
    <% if @user.invalid? %>
      <div class="alert-primary">
        <% @user.errors[:username].each do |message| %>
        <%= message %>
        <% end %>
      </div>
    <% end %>
    </p>
    <br>
    Your email address : <br>
    <input type="text" name="email"><br><br>
    The biography of your character : <br>
    <textarea name="bio"cols="30" rows="10"></textarea><br><br>
    <input type="submit" name="submit" value="Let's play !">
  </fieldset>
</form>